openapi: 3.0.1
info:
  title: Masterdata API
  version: 1.0.0
servers:
  - url: /api
tags:
  - name: Masterdata
paths:
  /{type}/search:
    post:
      tags:
        - Masterdata
      summary: Search Masterdata API
      description: Searches and retrives the list of Masterdata for a specific business type based on the query
      parameters:
        - name: type
          in: path
          required: true
          description: Business Type of the object.
          schema:
            type: string
          examples:
            Country:
              value: Country
      requestBody:
        description: Example of Request Payload as Resource
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Masterdata_Country_SEARCH_INPUT'
              required: 
                - type
        required: true
      responses:
        '200':
          description:   Returns the list of Masterdata as Bundle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Masterdata_Country_SEARCH_OUTPUT'
              example:
                type: Bundle
                total: 1
                entry: 
                  - id: aHR0cDovL3d3dy5pbm1pbmRjbG91ZC5kZXYuY29tL2FwcGxpY2F0aW9uL2FwcGxpY2F0aW9uLWltcGxlbWVudGF0aW9uLm93bCNBVA==
                    type: Country
                    uri: http://www.inmindcloud.dev.com/application/application-implementation.owl#AT
                    objectName: Austria
            
                    hasBaseCurrency: [ "http://www.inmindcloud.dev.com/application/application-implementation.owl#EUR"  ]
                    hasRegion: [ "http://www.inmindcloud.dev.com/application/application-implementation.owl#EMEA" ]
                      
  /{type}/:
    get:
      tags:
        - Masterdata
      summary: Searches and retrives the list of Masterdata for a specific business type
      description: >-
        Searches and retrives the list of Masterdata for a specific business type based on the query
      parameters:
        - name: type
          in: path
          required: true
          description: Business Type of the Masterdata
          schema:
            type: string
          examples:
            Country:
              value: Country
        - name: limit
          in: query
          description: >-
            For pagination, defines the maximum number of records that can be
            returned. If not specified, it will use default value of 200.
          schema:
            type: integer
            default: 200
        - name: offset
          in: query
          description: >-
            For pagination, defines the number of records that should be
            skipped. If not specified, no record will be skipped.
          schema:
            type: integer
            default: '0'
        - name: sort
          in: query
          description: Defines the sorting of the result. 'ASC' for ascending and 'DESC' for descending order. Default order is objectName ASC
          example: objectName ASC
          schema:
            type: string
            default: objectName ASC
        - name: filter
          in: query
          description: >-
            The filter parameter.
          examples:
            contains_operator:
              value: objectName contains '*usa'
              summary: contains
            equal_operator:
              value: >-
                objecname eq 'usa'
              summary: equal
            not_equal_operator:
              value: >-
                objecname ne 'usa'
              summary: not equal
            greater_than_operator:
              value: objectDateOfCreation gt 2020-03-20
              summary: greater than
            greater_than_eq_operator:
              value: objectDateOfCreation ge 2020-03-20
              summary: greater than equal
            less_than_operator:
              value: objectDateOfCreation lt 2020-03-20
              summary: less than
            less_than_eq_operator:
              value: objectDateOfCreation le 2020-03-20
              summary: less than equal
            and_operator:
              value: >-
                objectName contains '*usa' and objectId eq
                'us'
              summary: and
            or_operator:
              value: >-
                objectName contains '*usa' or objectId eq
                'us'
              summary: or
          schema:
            type: string
          explode: false
        - name: resolveRelations
          in: query
          description: >-
            To resolve nested data. Suppport multiple values with comma
            separated format.
          schema:
            type: string
          example: >-
            hasBaseCurrency,hasRegion,linksCountryRegion

      responses:
        default:
          description: >-
            By default, returns the list of Quotes without resolving any
            references and without any labels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Masterdata_Country_OUTPUT'
              example:
              - id: aHR0cDovL3d3dy5pbm1pbmRjbG91ZC5kZXYuY29tL2FwcGxpY2F0aW9uL2FwcGxpY2F0aW9uLWltcGxlbWVudGF0aW9uLm93bCNBVA==
                type: Country
                uri: 'http://www.inmindcloud.dev.com/application/application-implementation.owl#AT'
                objectName: Austria
                hasBaseCurrency: [ "http://www.inmindcloud.dev.com/application/application-implementation.owl#EUR" ]
                hasRegion: [ "http://www.inmindcloud.dev.com/application/application-implementation.owl#EMEA" ]
                
              
        x-resolveRelations:
          description: >-
            When parameter `resolveRelations` is provided, the related nested
            data will be resolved.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Masterdata_Country_OUTPUT_ALL'
              example:
                - id: aHR0cDovL3d3dy5pbm1pbmRjbG91ZC5kZXYuY29tL2FwcGxpY2F0aW9uL2FwcGxpY2F0aW9uLWltcGxlbWVudGF0aW9uLm93bCNBVA==
                  type: Country
                  uri: 'http://www.inmindcloud.dev.com/application/application-implementation.owl#AT'
                  objectName: Austria
                  hasBaseCurrency: [ "http://www.inmindcloud.dev.com/application/application-implementation.owl#EUR" ]
                  hasRegion: [ "http://www.inmindcloud.dev.com/application/application-implementation.owl#EMEA" ]
                      
  /{type}/count:
    get:
      tags:
        - Masterdata
      summary: Count the list of Masterdata based on filter
      description: >-
        Returns the number of records for the requested business type in the system.
      
      parameters:
        - name: type
          in: path
          required: true
          description: Sub type of Masterdata
          schema:
            type: string
          examples:
            Country:
              value: Country
            
        - name: filter
          in: query
          description: >-
            The filter parameter.
          examples:
            contains_operator:
              value: objectName contains '*usa'
              summary: contains
            equal_operator:
              value: >-
                objecname eq 'usa'
              summary: equal
            not_equal_operator:
              value: >-
                objecname ne 'usa'
              summary: not equal
            greater_than_operator:
              value: objectDateOfCreation gt 2020-03-20
              summary: greater than
            greater_than_eq_operator:
              value: objectDateOfCreation ge 2020-03-20
              summary: greater than equal
            less_than_operator:
              value: objectDateOfCreation lt 2020-03-20
              summary: less than
            less_than_eq_operator:
              value: objectDateOfCreation le 2020-03-20
              summary: less than equal
            and_operator:
              value: >-
                objectName contains 'usa' and objectId eq
                'us'
              summary: and
            or_operator:
              value: >-
                objectName contains 'usa' or objectId eq
                'us'
              summary: or
          schema:
            type: string
          explode: false

      responses:
        '200':
          description: Returns the number of masterdata of specific type.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Masterdata_Country_COUNT'
              example:
                count: 33
  '/{type}/{id}':
    get:
      tags:
        - Masterdata
      summary: Get the details of a Masterdata
      parameters:
        - name: type
          in: path
          required: true
          description: Sub type of Masterdata
          schema:
            type: string
          examples:
            Country:
              value: Country
              
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: base64-encoded URI
            example: >-
              aHR0cDovL2xvY2FsaG9zdDo4MDgwL2lzcy9RdW90ZSM2ZWNhMmQ2NTg1NmY0MzlmODI5MTE3Y2MzZGVhZGVlOQ==
        - name: resolveRelations
          in: query
          description: >-
            To resolve nested data. Suppport multiple values with comma
            separated format.
          schema:
            type: string
          example: >-
            hasBaseCurrency,hasRegion,linksCountryRegion
      responses:
        '200':
          description: >-
            Returns the details of quote.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Masterdata_Country_OUTPUT_ALL'
              example:
                - id: aHR0cDovL3d3dy5pbm1pbmRjbG91ZC5kZXYuY29tL2FwcGxpY2F0aW9uL2FwcGxpY2F0aW9uLWltcGxlbWVudGF0aW9uLm93bCNBVA==
                  type: Country
                  uri: 'http://www.inmindcloud.dev.com/application/application-implementation.owl#AT'
                  objectName: Austria
                  hasBaseCurrency: [ "http://www.inmindcloud.dev.com/application/application-implementation.owl#EUR" ]
                  hasRegion: [ "http://www.inmindcloud.dev.com/application/application-implementation.owl#EMEA" ]
                      
components:
  schemas:
    Masterdata_Country_COUNT:
      type: object
      properties:
        count:
          type: integer
          title: the number of masterdata of specific type
          example: 33
    Masterdata_Country_OUTPUT:
      type: object
      properties:
        id:
          type: string
          format: base64-encoded URI
          example: aHR0cDovL3d3dy5pbm1pbmRjbG91ZC5kZXYuY29tL2FwcGxpY2F0aW9uL2FwcGxpY2F0aW9uLWltcGxlbWVudGF0aW9uLm93bCNBVA==
        type:
          type: string
          example: Country
        objectName:
          type: string
          example: Austria
        hasBaseCurrency: 
          type: string
          format: URI
          example: The URI of country currency
        hasRegion: 
          type: string
          format: URI
          example: The URI of country region
            
    Masterdata_Country_SEARCH_INPUT:
      type: object
      properties:
        type: 
          type: string
          description: The type of the resource.
          example: Search
          default: 'Search'
        limit:
          type: integer
          description: Defines the maximum number of records that can be returned.
          example: 5
        offset:
          type: integer
          description: Defines the number of records that should be skipped. Default value is 0.
          default: 0
        filter:
          type: string
          example: 'objectName contains *usa'
          description: The filter parameter. If keyword contains space, it must be enclosed betwen two apostrophe('). If keyword is URI, it must be url encoded
        sort:
          description: Defines the sorting of the result. 'ASC' for ascending and 'DESC' for descending order. Default order is objectName ASC
          type: array
          items:
            type: string
            example: 'objectName DESC'
        elements:
          type: object
          description: >-
            Sets the BDAs and BRAs that will be returned. id, type, uri , label and comment are included by default. If 'elements' is not specified, all the BDAs and BRAs will be returned.
          properties:
            bda:
              type: string
              description: >-
                Defines the requested BDAs that will be returned. If set as empty string, only id, type, uri , label and comment will be returned.
              example: 
                - objectName
                - objectId
            bra:
              type: string
              description: >-
                Defines the requested BRAs that will be returned. If set as empty string, no BRAs will be returned. Ensure the BRA array contains all the dependent resources that are defined in 'include'.
              example: 
                - includesAddress
        include:
          description: Sets the related nested data that will be resolved.
          type: array
          items:
            type: string
            example: 'hasBaseCurrency'
        
    Masterdata_Country_SEARCH_OUTPUT:
      allOf:
        - $ref: '#/components/schemas/Masterdata_Country_OUTPUT'
            
    Masterdata_Country_OUTPUT_ALL:
      allOf:
        - $ref: '#/components/schemas/Masterdata_Country_OUTPUT'